### ISSUE TITLE
Killing Floor 2 - unable to locate protocols class for killing floor 2

### ISSUE THREAD

**Issue by Wesley21** [easy-wi/developer#1240]
Hi,

I'm having a weird issue with the GameQ part of this panel. It's working fine for all games except KF2. 

I'm getting the following error:

`PHP Fatal error:  Uncaught GameQ\Exception\Server: Unable to locate Protocols class for 'killing floor 2'! in /home/easywi_web/htdocs/third_party/gameq/GameQ/Server.php:146`

Would be great if there is a fix available.

**Comment by R3belWithoutAPause** [comment]
Could you give me some information please:
Which OS are you using and what version is it?
What version of the panel are you using ? Is it stable or developer ?
Were you doing anything in particular when this happened ?

**Comment by Wesley21** [comment]
Sure,

Running Ubuntu 18.04 LTS
Panel is at version 6.0.5, Stable

I was wondering why the player stats/map name wasn't updating, so I ran "cd /home/easywi_web/htdocs && timeout 290 php ./statuscheck.php" manually to see if there were any errors and it showed me the above. I did make a Killing Floor 2 Game Server Template and selected Killing Floor 2 at the GameQ dropdown.

**Comment by R3belWithoutAPause** [comment]
Thanks.
I will see if i can reproduce this tomorrow.

**Comment by MikkelDK** [comment]
Hi @Wesley21 .

Could you share the KillingFloor 2 template with us? so we can check, what we need to update! =D

**Comment by Wesley21** [comment]
Sure, I zipped the file because .xml can't be attached.

[kf2.zip](https://github.com/easy-wi/developer/files/4716878/kf2.zip)

**Comment by Wesley21** [comment]
Sure :)

I zipped the .xml because .xml isn't supported for uploading/attaching here.


[kf2.zip](https://github.com/easy-wi/developer/files/4716890/kf2.zip)

**Comment by MikkelDK** [comment]
Ok, we figure out.

Killing Floor 2 = KF2 doesn't support GameQ v2. and need to be converted to GameQ v3.

**Comment by Wesley21** [comment]
It appears to be using GameQ v3. IP addres has been replaced by xxxx.

Output:

` cd /home/easywi_web/htdocs && timeout 290 php ./statuscheck.php
Checking Gameserver, Voiceserver MySQL DB sizes and Web Quotas
GameQ v3 support for csgo xxxx:27015
GameQ v3 support for rust xxxx:27025
GameQ v3 support for csgo xxxx:27035
GameQ v3 support for kf2 xxxx:7777
Checking 4 server(s) with GameQ v3 query
PHP Fatal error:  Uncaught GameQ\Exception\Server: Unable to locate Protocols class for 'killing floor 2'! in /home/easywi_web/htdocs/third_party/gameq/GameQ/Server.php:146
Stack trace:
#0 /home/easywi_web/htdocs/third_party/gameq/GameQ/GameQ.php(189): GameQ\Server->__construct(Array)
#1 /home/easywi_web/htdocs/third_party/gameq/GameQ/GameQ.php(206): GameQ\GameQ->addServer(Array)
#2 /home/easywi_web/htdocs/statuscheck.php(328): GameQ\GameQ->addServers(Array)
#3 {main}
  thrown in /home/easywi_web/htdocs/third_party/gameq/GameQ/Server.php on line 146
`

GameQ v2 is in folder gameq_v2 and v3 is in folder gameq/GameQ.

**Comment by MikkelDK** [comment]
@Wesley21 I see.

Seems it can't figure "`Unable to locate Protocols class for 'killing floor 2'`"

**Comment by Wesley21** [comment]
> @Wesley21 I see.
> 
> Seems it can't figure "`Unable to locate Protocols class for 'killing floor 2'`"

I'm sorry but what do you mean exactly? I can see that it's unable to locate protocols class for killing floor 2.. 

I'm trying to get this fixed but I have no idea where to look for since I can not find anything regarding that class in the GameQ source code.

**Comment by Wesley21** [comment]
Alright.. The problem with the errors has been fixed now. I have changed protected $name = 'killing floor 2'; to protected $name = 'killingfloor2'; in Killingfloor2.php (GameQ/Protocols).

But.. A new problem appears, the script keeps restarting my server now because it can not query it somehow I think..

**Comment by MikkelDK** [comment]
Let me try to look! =)
