### ISSUE TITLE
Minecraft Server multiple arguments[o,online-mode]

### ISSUE THREAD

**Issue by Scottvishnu** [easy-wi/developer#750]
>
Loading libraries, please wait...
>
[13:47:11 INFO]: Starting minecraft server version 1.8.8
>
[13:47:11 INFO]: Loading properties
>
[13:47:11 ERROR]: Encountered an unexpected exception
org.bukkit.craftbukkit.libs.joptsimple.MultipleArgumentsForOptionException: Found multiple arguments for option ['o', 'online-mode'], but you asked for only one
at org.bukkit.craftbukkit.libs.joptsimple.OptionSet.valueOf(OptionSet.java:177) ~[craftbukkit.jar:git-Bukkit-039621d]
at org.bukkit.craftbukkit.libs.joptsimple.OptionSet.valueOf(OptionSet.java:149) ~[craftbukkit.jar:git-Bukkit-039621d]
at net.minecraft.server.v1_8_R3.PropertyManager.getOverride(PropertyManager.java:58) ~[craftbukkit.jar:git-Bukkit-039621d]
at net.minecraft.server.v1_8_R3.PropertyManager.getBoolean(PropertyManager.java:138) ~[craftbukkit.jar:git-Bukkit-039621d]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:133) ~[craftbukkit.jar:git-Bukkit-039621d]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:504) [craftbukkit.jar:git-Bukkit-039621d]
at java.lang.Thread.run(Thread.java:701) [?:1.6.0_38]
>
[13:47:11 ERROR]: This crash report has been saved to: /home/user2-1/server/81.7.--.1-6_25565/bukkit/./crash-reports/crash-2016-02-27_13.47.11-server.txt
>
[13:47:11 INFO]: Stopping server
>[m

verursacht durch:

[Onlinemode On = default]
-o true

[Onlinemode Off]
-o false

**Comment by Qhiliqq** [comment]
Kann ich nicht reproduzieren.
Weder mit Craftbukkit, noch Vanilla, noch Spigot, noch irgendwelche Forge versionen (FTB etc)
